config/routes.rb
Hyakuman::Application.routes.draw do
  resources :productlines
  resources :manufacturers
  resources :materials

end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :productline
  belongs_to :manufacturer#, :through => :productline
  attr_accessible :image, :name, :productline_id, :manufacturer_id
  validates_presence_of :productline_id, :manufacturer_id
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materials }
    end
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @material = Material.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/new
  # GET /materials/new.json
  def new
    @material = Material.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/1/edit
  def edit
    @material = Material.find(params[:id])
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(params[:material])

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render json: @material, status: :created, location: @material }
      else
        format.html { render action: "new" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materials/1
  # PUT /materials/1.json
  def update
    @material = Material.find(params[:id])

    respond_to do |format|
      if @material.update_attributes(params[:material])
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br />
	<%= f.collection_select :manufacturer_id, Manufacturer.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :productline_id %><br />
	<%= f.grouped_collection_select :productline_id, Manufacturer.order(:name), :productlines, :name, :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manufacturer</th>
    <th>Productline</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materials.each do |material| %>
  <tr>
    <td><%= material.name %></td>
    <td><%= material.manufacturer.name %></td>
    <td><%= material.productline.name %></td>
    <td><%= material.image %></td>
    <td><%= link_to 'Show', material %></td>
    <td><%= link_to 'Edit', edit_material_path(material) %></td>
    <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @material.name %>
</p>
<p>
  <b>Manufacturer:</b>
  <%= @material.manufacturer.try(:name) %>
</p>
<p>
  <b>Productline:</b>
  <%= @material.productline.try(:name) %>
</p>

<p>
  <b>Image:</b>
  <%= @material.image %>
</p>


<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>