config/routes.rb
Hyakuman::Application.routes.draw do
  resources :productlines
  resources :manufacturers
  resources :materials

end

app/models/productline.rb
class Productline < ActiveRecord::Base
  belongs_to :manufacturer
  has_many :materials
  attr_accessible :name, :manufacturer_id
end

app/controllers/productlines_controller.rb
class ProductlinesController < ApplicationController
  # GET /productlines
  # GET /productlines.json
  def index
    @productlines = Productline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productlines }
    end
  end

  # GET /productlines/1
  # GET /productlines/1.json
  def show
    @productline = Productline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @productline }
    end
  end

  # GET /productlines/new
  # GET /productlines/new.json
  def new
    @productline = Productline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @productline }
    end
  end

  # GET /productlines/1/edit
  def edit
    @productline = Productline.find(params[:id])
  end

  # POST /productlines
  # POST /productlines.json
  def create
    @productline = Productline.new(params[:productline])

    respond_to do |format|
      if @productline.save
        format.html { redirect_to @productline, notice: 'Productline was successfully created.' }
        format.json { render json: @productline, status: :created, location: @productline }
      else
        format.html { render action: "new" }
        format.json { render json: @productline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productlines/1
  # PUT /productlines/1.json
  def update
    @productline = Productline.find(params[:id])

    respond_to do |format|
      if @productline.update_attributes(params[:productline])
        format.html { redirect_to @productline, notice: 'Productline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @productline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productlines/1
  # DELETE /productlines/1.json
  def destroy
    @productline = Productline.find(params[:id])
    @productline.destroy

    respond_to do |format|
      format.html { redirect_to productlines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/productlines_helper.rb
module ProductlinesHelper
end

app/views/productlines/_form.html.erb
<%= form_for(@productline) do |f| %>
  <% if @productline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@productline.errors.count, "error") %> prohibited this productline from being saved:</h2>

      <ul>
      <% @productline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br />
	<%= f.collection_select :manufacturer_id, Manufacturer.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productlines/edit.html.erb
<h1>Editing productline</h1>

<%= render 'form' %>

<%= link_to 'Show', @productline %> |
<%= link_to 'Back', productlines_path %>

app/views/productlines/index.html.erb
<h1>Listing productlines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manufacturer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productlines.each do |productline| %>
  <tr>
    <td><%= productline.name %></td>
    <td><%= productline.manufacturer.name %></td>
    <td><%= link_to 'Show', productline %></td>
    <td><%= link_to 'Edit', edit_productline_path(productline) %></td>
    <td><%= link_to 'Destroy', productline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Productline', new_productline_path %>

app/views/productlines/new.html.erb
<h1>New productline</h1>

<%= render 'form' %>

<%= link_to 'Back', productlines_path %>

app/views/productlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @productline.name %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @productline.manufacturer.try(:name) %>
</p>


<%= link_to 'Edit', edit_productline_path(@productline) %> |
<%= link_to 'Back', productlines_path %>